name: Upload to R2
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Upload to Cloudflare R2
        run: |
          aws s3 sync ./assets/ s3://derrickdryer-assets --endpoint-url https://6fe3afc93b8ec1ebe95d00ab70fc80bd.r2.cloudflarestorage.com/derrickdryer-assets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
